{% set name = "callstate" %}
{% set version = "0.0.1" %}
{% set sha256hash = "e28a21305ead3733ffb3b5266899e34067ce91f14eca1666a95d22b42371df0a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/LuobinY/Callstate/archive/v{{ version }}.tar.gz
    sha256: {{ sha256hash }}
  - url: https://nim-lang.org/download/nim-1.0.6.tar.xz
    sha256: 134e5751cf62fa189f76616a698ce0df4b4a0c1419ec0b582924087e585f66b3
    folder: nim_source

build:
  number: 0
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pcre
    - htslib
  run:
    - pcre
    - htslib

test:
  commands:
    - mosdepth -h

about:
  home: https://github.com/LuobinY/Callstate
  license: MIT
  summary: 'A replacement for GATK3 CallableLoci'
